version: "3.9"

services:
  db-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - my_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      db-network:
        aliases:
          - ssdmsbase
    container_name: db-mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  db-network:
    name: "db-network"

volumes:
  my_data:
    name: "my_data"
